name: Build and Deploy React Frontend to EC2

on:
  push:
    branches:
      - main  # یا branch دلخواه شما

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: |
          CI=false npm run build

      - name: Copy build folder to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ec2-user/frontend"
